[package]
name = "service_observer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
crossterm = "0.25.0"
ctrlc = "3.2.3"
journal_parser ={ path = "../journal_parser"}
sshd_logs ={ path = "../sshd_logs"}
tui = "0.19.0"
