//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "geolocation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub latitude: f64,
    pub longitude: f64,
    pub created: String,
    pub ip_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ip::Entity",
        from = "Column::IpId",
        to = "super::ip::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ip,
}

impl Related<super::ip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ip.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
