//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ip")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ipv4: String,
    pub created: String,
    pub updated: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::geolocation::Entity")]
    Geolocation,
}

impl Related<super::geolocation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Geolocation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
