[package]
name = "sshd_logs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
journal_parser ={ path = "../journal_parser"}
rayon = "1.8.0"
regex = "1.10.2"
thiserror = "1.0.50"
